name: generate

on: 
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
    generatesrs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: setup singbox
          env:
            SINGBOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.9.3/sing-box_1.9.3_linux_amd64.deb"
          run: |
            wget -O sing-box.deb $SINGBOX_DEB_URL
            sudo dpkg -i sing-box.deb
        - name: generate singbox config
          run: |
            mkdir srs
            for file in *.json; do
              filename=$(basename "$file" .json)
              sing-box rule-set compile "$file" -o "srs/$filename.srs"
            done
        - name: Commit and push *.srs
          run: |
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git add srs
            if git diff --staged --quiet; then
              echo "No changes to commit"
              exit 0
            else
              git commit -m "Generate srs files"
              echo "commit message: Generate srs files"
              git push 
            fi



